server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - uri: http://localhost:8080
          predicates:
            - Path=/goods/**
        - uri: http://localhost:8081
          predicates:
            - Path=/orders/**
        - uri: http://localhost:8083
          predicates:
            - Path=/kill/**
          filters:
            - TokenLimiter