server:
  port: 20000
spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:20000/erueka
    fetch-registry: false
security:
  basic:
    enabled: false